### ISSUE TITLE
Broken Result and Option links

### ISSUE THREAD

**Issue by stanleygjones** [dfinity/docs#122]
From Tungsten Hackathon:

> "Broken links to “Result” , “Option” and “error-types” from this page
https://sdk.dfinity.org/docs/language-guide/errors-and-options.html"

**Comment by lsgunnlsgunn** [comment]
Can't seem to link to a PR that's in another repo
https://github.com/dfinity-lab/motoko/pull/1665

**Comment by lsgunnlsgunn** [comment]
Merged fix is in another repo
