### ISSUE TITLE
Bug in Example

### ISSUE THREAD

**Issue by idkjs** [dfinity/docs#200]
I cant seem to find the place to ask this question. I am unable to make a comment in the forum for some reason.
In the docs at [#_revise_the_source_code_in_your_program](https://sdk.dfinity.org/docs/developers-guide/tutorials/hello-location.html#_revise_the_source_code_in_your_program)

After changing the code, building and reinstalling I get this type error:

```sh
~/Downloads/MOKOTO/location_hello master*
❯ dfx build && dfx canister install favorite_cities -m reinstall
Building canisters...
Installing code for canister favorite_cities, with canister_id cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q

~/Downloads/MOKOTO/location_hello master*
❯ dfx canister call favorite_cities location '(vec {"San Francisco";"Paris";"Rome"})'

```

`main.mo`
```mo
actor {
    public func location(cities : [Text]) : async Text {
        return "Hello, from " # (debug_show cities) # "!";
    };
    public func location_pretty(cities : [Text]) : async Text {
        var str = "Hello from ";
        for (city in cities.vals()) {
                str := str # city #", ";
        };
        return str # "bon voyage!";
    }
};
```

Also, do I have to rebuild everytime I make a change?

Thank you.

Disregard. I had to change directories and fix the path in `dfx.json`. 

Thank you. Please do tell where I should be posting this and all about rebuilding. Thank you.

**Comment by lsgunnlsgunn** [comment]
You do need to rebuild if you make changes to the code because the build step compiles the code into WebAssembly--which is required before you can deploy the program as a canister on the Internet Computer.

I'm not sure why you are having problems posting on the forum, which is a great place to ask questions and look for developer tips.

**Comment by idkjs** [comment]
> I'm not sure why you are having problems posting on the forum, which is a great place to ask questions and look for developer tips.

Apparently, you have to be approved by the system which has since happened. Thanks!
