### ISSUE TITLE
wrong link in documentation

### ISSUE THREAD

**Issue by Daft-Wullie** [dfinity/docs#328]
If i scroll down all the way on the *Principals and caller identification* page at https://sdk.dfinity.org/docs/language-guide/caller-id.html and follow the Principal link in "*More operations on principals are available in [Principal](https://sdk.dfinity.org/docs/base-libraries/result.html) base library.*" it takes me to https://sdk.dfinity.org/docs/base-libraries/result instead of what was probably the intended page eg https://sdk.dfinity.org/docs/base-libraries/principal

**Comment by nomeata** [comment]
Thanks! The original copy of that file is in an internal repository, but I have fixed it there, and it will make its way to the public docs pages eventually.

**Comment by lsgunnlsgunn** [comment]
Thanks!
