### ISSUE TITLE
Array.Flatten missing parameter type

### ISSUE THREAD

**Issue by ililic** [dfinity/docs#363]
https://sdk.dfinity.org/docs/base-libraries/array#flatten

I believe the method signature should be 
`func flatten<A>(xs : [[A]]) : [A]`

**Comment by lsgunnlsgunn** [comment]
Added this as an issue to the motoko-base repo:
https://github.com/dfinity/motoko-base/issues/239

**Comment by lsgunnlsgunn** [comment]
Fixed in https://github.com/dfinity/motoko-base/issues/239

**Comment by lsgunnlsgunn** [comment]
Updated doc deployed on the website
