### ISSUE TITLE
Hello, World! Rust CDK Quick Start Issues

### ISSUE THREAD

**Issue by ililic** [dfinity/docs#420]
**Describe the bug**
This bug report will detail issues found in the [Hello, World! Rust CDK Quick Start](https://sdk.dfinity.org/docs/rust-guide/rust-quickstart.html)

**To Reproduce**

1. `ls -l cdk_rs/src` returns `ls: cdk_rs/src: No such file or directory` ; instead it should be `ls -l cdk-rs/src` which the expected. ✅ 
2. `To modify the Cargo.toml configuration file` should say `To modify (or create) the Cargo.toml configuration file` since folks using Dfx will need to create one ✅ 
3. > Use the [workspace] key to specify the source file directories for your program.
[workspace] should be a code block (since previous keys were in code blocks): `[workspace]` ✅ 
4. Version bump the second Cargo.toml (within the src directory). Was:
```
[package]
name = "rust_hello"
version = "0.1.0"
authors = ["Your Name <your-email@example.com>"]
edition = "2018"

[lib]
path = "main.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { path = "../../../cdk-rs/src/ic-cdk", version = "0.1.0" }
ic-cdk-macros = { path = "../../../cdk-rs/src/ic-cdk-macros", version = "0.1.0" }
```
should be:
```
[package]
name = "rust_hello"
version = "0.1.0"
authors = ["Your Name <your-email@example.com>"]
edition = "2018"

[lib]
path = "main.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { path = "../../../cdk-rs/src/ic-cdk", version = "0.2.4" }
ic-cdk-macros = { path = "../../../cdk-rs/src/ic-cdk-macros", version = "0.2.4" }

```

**New Additions**

1. Users need to install the ic-cdk-optimizer in order to ensure that their rust code is sufficiently small for uploading as a canister:  `cargo install ic-cdk-optimizer`
2. Users need to make a release directory within their `rust_hello` directory: `mkdir -p target/wasm32-unknown-unknown/release/`
3. Users need to optimize their code. From the `rust_hello` directory: `ic-cdk-optimizer target/wasm32-unknown-unknown/debug/rust_hello.wasm -o target/wasm32-unknown-unknown/release/rust_hello-opt.wasm `
4. Users need to update their `dfx.json` to point to the optimized wasm in the `canisters.rust_hello.wasm` key: `"wasm": "target/wasm32-unknown-unknown/release/rust_hello-opt.wasm"`

**Comment by lsgunnlsgunn** [comment]
This didn't work for me:
`cargo install ic-cdk-optimizer`

I think there are still steps missing.

**Comment by ililic** [comment]
Oh… can you drop the error msg here?

**Comment by lsgunnlsgunn** [comment]
Tutorials have been updated.
