### ISSUE TITLE
Move Motoko docs into `motoko` repo

### ISSUE THREAD

**Issue by stanleygjones** [dfinity/docs#46]

**Comment by lsgunnlsgunn** [comment]
The infrastructure (playbook) for doing this ready to go and tested locally, but the repo needs to be public or we need a credential workaround to make it happen.

The motoko docs will actually be moved in two phases: 
- the motoko-base repo (playbook ready, local testing works)
    TODO:  
- [ ] Finish the script that generates base library files
- [ ] Add the script  that creates .adoc files from .mo files to the antora pre-processor
- [ ] Uncomment settings in the playbook
- the motoko repo (playbook ready, local testing works)

    TODO:  

- [ ] Make motoko public or get credentials working
- [ ] Move Language guide files to motoko and delete them from docs
- [ ] Uncomment settings in the playbook

**Comment by lsgunnlsgunn** [comment]
The process for the base library is still manual, but the doc source has been moved to the motoko and motoko-base repos.
