### ISSUE TITLE
Fix minor issues in Antora structure/placeholder files

### ISSUE THREAD

**Issue by stanleygjones** [dfinity/docs#47]
From JIRA:
- [x] Fix Quick start links.
- [x] Fix Download page to include instructions / hide future options
- [x] Change tile headings and descriptions
- [x] Fix language guide links.

**Comment by lsgunnlsgunn** [comment]
Internal language guide links still need to be cleaned up, but the rest are all done so it would be better to tackle the Lang links section by section instead of in this bucket.
