### ISSUE TITLE
Incorrect boilerplate in "Explore the default project"

### ISSUE THREAD

**Issue by johanforslund** [dfinity/docs#485]
The tutorial named [Explore the default project](https://sdk.dfinity.org/docs/developers-guide/tutorials/explore-templates.html) says that there will be a "src" folder in explore_hello_assets with two files. When I generate a new project with `dfx new` , the folder is named "public" instead and does not contain any HTML, only this index.js

```
import explore_hello from 'ic:canisters/explore_hello';

explore_hello.greet(window.prompt("Enter your name:")).then(greeting => {
  window.alert(greeting);
});
```

Using dfx 0.6.26.

**Comment by ggreif** [comment]
Related and possibly relevant: https://github.com/nop33/dfinity-vue/issues/3

**Comment by lsgunnlsgunn** [comment]
https://sdk.dfinity.org/docs/http-middleware.html

**Comment by lsgunnlsgunn** [comment]
The docs reflect the post 0.6.26 directory structure. If you install (or update) `dfx` to the latest version now, your directory structure should match what's in the documentation. 
Thanks for reporting the issue! If you see anything amiss after installing a new version, please do open a new issue.
