### ISSUE TITLE
Unable to Install Dfinity SDK on Mac: Protocol "http" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by ziaukhan** [dfinity/docs#574]
Mac OS Big Sur version 11.4

curl --version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

git --version
git version 2.33.0

ziamac:~ ZiaKhan$ sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

info: Executing DFINITY SDK install script, commit: 93a5bbe24750abf12eb61857709ccabf6392d662
The DFINITY Canister SDK
Copyright 2021 DFINITY Stiftung. All Rights Reserved.
The DFINITY Canister SDK (the "Software") is licensed under the Alpha DFINITY
Canister SDK License Agreement (the "License"). You may not use the Software
except in compliance with the License. You may obtain a copy of the License at
    https://sdk.dfinity.org/sdk-license-agreement.txt
The Software is provided to you AS IS and WITHOUT WARRANTY.
Do you agree and wish to install the DFINITY Canister SDK [y/N]?
Please accept the license to continue.
exit
ziamac:~ ZiaKhan$ sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
info: Executing DFINITY SDK install script, commit: 93a5bbe24750abf12eb61857709ccabf6392d662
The DFINITY Canister SDK
Copyright 2021 DFINITY Stiftung. All Rights Reserved.
The DFINITY Canister SDK (the "Software") is licensed under the Alpha DFINITY
Canister SDK License Agreement (the "License"). You may not use the Software
except in compliance with the License. You may obtain a copy of the License at
    https://sdk.dfinity.org/sdk-license-agreement.txt
The Software is provided to you AS IS and WITHOUT WARRANTY.
Do you agree and wish to install the DFINITY Canister SDK [y/N]?
y
curl: (1) Protocol "http" not supported or disabled in libcurl
info: Version found: 
info: Creating uninstall script in ~/.cache/dfinity
info: uninstall path=/Users/ZiaKhan/.cache/dfinity/uninstall.sh
info: Checking for latest release...
curl: (1) Protocol "http" not supported or disabled in libcurl
dfinity-sdk: command failed: downloader https://sdk.dfinity.org/downloads/dfx//x86_64-darwin/dfx-.tar.gz /var/folders/yv/zct07nhn2vz231992hr690480000gn/T/tmp.B5AjloY9/dfx.tar.gz
exit

**Comment by albertcsg** [comment]
same

**Comment by albertcsg** [comment]
try this
https://smartcontracts.org/docs/token-holders/seed-donations.html#_install_keysmith

https://github.com/dfinity/keysmith/releases/tag/v1.5.0

**Comment by albertcsg** [comment]
it works
https://download.dfinity.systems/sdk/dfx/0.6.22/x86_64-darwin/dfx-0.6.22.tar.gz

**Comment by ziaukhan** [comment]
It is working, but is there no way to run latest version?
dfx --version
dfx 0.6.22

**Comment by ziaukhan** [comment]
dfx upgrade did the trick
