### ISSUE TITLE
Old, more comprehensive examples pages MIA

### ISSUE THREAD

**Issue by crusso** [dfinity/docs#635]
https://github.com/dfinity/docs/blob/main/modules/developers-guide/pages/sample-apps.adoc

was an old page listing examples. It appears to have been dropped from the website, perhaps it's missing an entry here:

https://github.com/dfinity/docs/blob/main/modules/ROOT/nav.adoc

**Comment by crusso** [comment]
Perhaps some of the examples should be moved the newer page here:

https://github.com/dfinity/docs/blob/main/modules/examples/pages/index.adoc

**Comment by crusso** [comment]
@krpeacock whaddya think?

**Comment by krpeacock** [comment]
I didn't know this page was here!

As for the direction of the examples page, I think we want it to be a little more curated, trying to provide reference code to specific types of applications that people are coming in for.

Eventually, it would be great to have a system where people can quickly discover examples for "how do I do X" in any framework we support, but for the meantime, I think it's best to try and reduce decision fatigue and to try to map each example to a distinct developer story

**Comment by crusso** [comment]
@krpeacock Matthew Hammer actually added such a guide to the Motoko examples https://github.com/dfinity/examples/blob/master/motoko/README.md

**Comment by krpeacock** [comment]
Oh cool! I'm not planning on going out of my way to continue contributing to the page right now, but feel free to migrate over any examples you find important
