### ISSUE TITLE
Add tools like ic-admin to the docs

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/docs#728]
There are a couple of tools hidden in the ic repo that are not documented such as [`ic-admin`](https://github.com/dfinity/ic/tree/master/rs/registry/admin) or [icx-asset](https://github.com/dfinity/agent-rs/tree/main/icx-asset) . 

Please add them to the docs.

**Comment by domwoe** [comment]
Thx! Would be great to collect the tools that are hidden. Please add, if you are aware of any more tools that are helpful for developers.
